before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python2.7 patch pkg-config libbz2-1.0
  - git clone https://github.com/nidium/NidiumTools.git

compiler: clang


script:
  -  ASAN_OPTIONS=detect_leaks=0 PYTHONPATH=./NidiumTools/src ./configure_server --debug --asan --no-fork --unit-tests --assume-yes

cache:
  directories:
  - third-party

language: cpp
