before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python2.7 patch pkg-config libbz2-1.0
  - git clone https://github.com/nidium/NidiumTools.git

compiler: clang


script: PYTHONPATH=./NidiumTools/src ./configure_server --debug --no-fork

cache:
  directories:
  - third-party

language: cpp